name: 1.18 Auto Build Release Publish

on:
  watch:
    types: [ started ]
  push:
    branches:
      - 'exp-1.18'
    paths:
      - 'version.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
          
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build publish

    - name: Get file name
      id: var
      run: |
        MESSAGE=$(ls build/libs/* | grep sources.jar -v)
        echo file_path=$MESSAGE >> $GITHUB_OUTPUT

    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: xupdate_apk
        path: ${{ github.workspace }}/app/build/outputs/apk/release
